DEFAULT:
  perform_check: yes
  allowed_licenses:
    - Apache-2.0
  license_for_new_files: Apache-2.0
  new_notice_c: |
    /*
     * SPDX-FileCopyrightText: {years} Espressif Systems (Shanghai) CO LTD
     *
     * SPDX-License-Identifier: {license}
     */
  new_notice_python: |
    # SPDX-FileCopyrightText: {years} Espressif Systems (Shanghai) CO LTD
    # SPDX-License-Identifier: {license}
  espressif_copyright: '{years} Espressif Systems (Shanghai) CO LTD'

mixology_library:
  perform_check: yes
  include:
    - 'idf_component_manager/version_solver/mixology/**'
  allowed_licenses:
    - MIT License
    - Apache-2.0  # For new files

semver_library:
  perform_check: yes
  include:
    - 'idf_component_tools/semver/**'
    - 'tests/semver/**'
  allowed_licenses:
    - BSD 2-Clause License
    - Apache-2.0  # For new files
