stages:
  - test
  - integration_test

workflow:
  rules:
    - when: always

test:
  stage: test
  tags:
    - test
    - internet
  parallel:
    matrix:
      - PYTHON_IMAGE_TAG: [2.7-buster, 3.4-stretch, 3.5-buster, 3.11-bullseye]
  image: python:${PYTHON_IMAGE_TAG}
  before_script:
    - pip install pytest pytest-cov pytest-mock vcrpy .
  script:
    - py.test --cov=. --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
